// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package hoopoe

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

// CreateMatchingCheckArea includes the requested fields of the GraphQL type Area.
type CreateMatchingCheckArea struct {
	// 地区代码
	Code string `json:"code"`
	// 是否开通业务
	Enabled bool `json:"enabled"`
}

// GetCode returns CreateMatchingCheckArea.Code, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckArea) GetCode() string { return v.Code }

// GetEnabled returns CreateMatchingCheckArea.Enabled, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckArea) GetEnabled() bool { return v.Enabled }

// CreateMatchingCheckLevelDetail includes the requested fields of the GraphQL type LevelDetail.
type CreateMatchingCheckLevelDetail struct {
	// 当前等级的权益
	Rights *CreateMatchingCheckLevelDetailRightsLevelRights `json:"rights"`
}

// GetRights returns CreateMatchingCheckLevelDetail.Rights, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckLevelDetail) GetRights() *CreateMatchingCheckLevelDetailRightsLevelRights {
	return v.Rights
}

// CreateMatchingCheckLevelDetailRightsLevelRights includes the requested fields of the GraphQL type LevelRights.
type CreateMatchingCheckLevelDetailRightsLevelRights struct {
	// 性别选择
	GenderSelection bool `json:"genderSelection"`
}

// GetGenderSelection returns CreateMatchingCheckLevelDetailRightsLevelRights.GenderSelection, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckLevelDetailRightsLevelRights) GetGenderSelection() bool {
	return v.GenderSelection
}

// CreateMatchingCheckResponse is returned by CreateMatchingCheck on success.
type CreateMatchingCheckResponse struct {
	// 【话题】话题查询
	Topic *CreateMatchingCheckTopic `json:"topic"`
	// 【地区】根据地区代码查询地区信息
	Area *CreateMatchingCheckArea `json:"area"`
	// 【用户】获取用户信息
	User *CreateMatchingCheckUser `json:"user"`
	// 【用户】 用户信息完整性检查
	UserInfoCompletenessCheck *CreateMatchingCheckUserInfoCompletenessCheckUserInfoCompleteness `json:"userInfoCompletenessCheck"`
	// 【用户】等级详情
	LevelDetail *CreateMatchingCheckLevelDetail `json:"levelDetail"`
}

// GetTopic returns CreateMatchingCheckResponse.Topic, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckResponse) GetTopic() *CreateMatchingCheckTopic { return v.Topic }

// GetArea returns CreateMatchingCheckResponse.Area, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckResponse) GetArea() *CreateMatchingCheckArea { return v.Area }

// GetUser returns CreateMatchingCheckResponse.User, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckResponse) GetUser() *CreateMatchingCheckUser { return v.User }

// GetUserInfoCompletenessCheck returns CreateMatchingCheckResponse.UserInfoCompletenessCheck, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckResponse) GetUserInfoCompletenessCheck() *CreateMatchingCheckUserInfoCompletenessCheckUserInfoCompleteness {
	return v.UserInfoCompletenessCheck
}

// GetLevelDetail returns CreateMatchingCheckResponse.LevelDetail, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckResponse) GetLevelDetail() *CreateMatchingCheckLevelDetail {
	return v.LevelDetail
}

// CreateMatchingCheckTopic includes the requested fields of the GraphQL type Topic.
type CreateMatchingCheckTopic struct {
	// 话题ID
	Id string `json:"id"`
	// 是否可用
	Enable bool `json:"enable"`
}

// GetId returns CreateMatchingCheckTopic.Id, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckTopic) GetId() string { return v.Id }

// GetEnable returns CreateMatchingCheckTopic.Enable, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckTopic) GetEnable() bool { return v.Enable }

// CreateMatchingCheckUser includes the requested fields of the GraphQL type User.
type CreateMatchingCheckUser struct {
	// 用户封禁信息
	BlockInfo *CreateMatchingCheckUserBlockInfo `json:"blockInfo"`
}

// GetBlockInfo returns CreateMatchingCheckUser.BlockInfo, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckUser) GetBlockInfo() *CreateMatchingCheckUserBlockInfo {
	return v.BlockInfo
}

// CreateMatchingCheckUserBlockInfo includes the requested fields of the GraphQL type UserBlockInfo.
type CreateMatchingCheckUserBlockInfo struct {
	// 是否用户封禁，封禁则整个APP无法使用
	UserBlocked bool `json:"userBlocked"`
	// 是否匹配封禁，封禁则无法加入新的匹配
	MatchingBlocked bool `json:"matchingBlocked"`
}

// GetUserBlocked returns CreateMatchingCheckUserBlockInfo.UserBlocked, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckUserBlockInfo) GetUserBlocked() bool { return v.UserBlocked }

// GetMatchingBlocked returns CreateMatchingCheckUserBlockInfo.MatchingBlocked, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckUserBlockInfo) GetMatchingBlocked() bool { return v.MatchingBlocked }

// CreateMatchingCheckUserInfoCompletenessCheckUserInfoCompleteness includes the requested fields of the GraphQL type UserInfoCompleteness.
type CreateMatchingCheckUserInfoCompletenessCheckUserInfoCompleteness struct {
	// 信息是否全部填写
	Filled bool `json:"filled"`
}

// GetFilled returns CreateMatchingCheckUserInfoCompletenessCheckUserInfoCompleteness.Filled, and is useful for accessing the field via an interface.
func (v *CreateMatchingCheckUserInfoCompletenessCheckUserInfoCompleteness) GetFilled() bool {
	return v.Filled
}

// CreateMatchingInvitationCheckArea includes the requested fields of the GraphQL type Area.
type CreateMatchingInvitationCheckArea struct {
	// 地区代码
	Code string `json:"code"`
	// 是否开通业务
	Enabled bool `json:"enabled"`
}

// GetCode returns CreateMatchingInvitationCheckArea.Code, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckArea) GetCode() string { return v.Code }

// GetEnabled returns CreateMatchingInvitationCheckArea.Enabled, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckArea) GetEnabled() bool { return v.Enabled }

// CreateMatchingInvitationCheckBlacklistRelationshipUserPair includes the requested fields of the GraphQL type UserPair.
type CreateMatchingInvitationCheckBlacklistRelationshipUserPair struct {
	A string `json:"a"`
	B string `json:"b"`
}

// GetA returns CreateMatchingInvitationCheckBlacklistRelationshipUserPair.A, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckBlacklistRelationshipUserPair) GetA() string { return v.A }

// GetB returns CreateMatchingInvitationCheckBlacklistRelationshipUserPair.B, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckBlacklistRelationshipUserPair) GetB() string { return v.B }

// CreateMatchingInvitationCheckGetUserByIdsV2User includes the requested fields of the GraphQL type User.
type CreateMatchingInvitationCheckGetUserByIdsV2User struct {
	// 用户ID
	Id string `json:"id"`
	// 用户封禁信息
	BlockInfo *CreateMatchingInvitationCheckGetUserByIdsV2UserBlockInfo `json:"blockInfo"`
}

// GetId returns CreateMatchingInvitationCheckGetUserByIdsV2User.Id, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckGetUserByIdsV2User) GetId() string { return v.Id }

// GetBlockInfo returns CreateMatchingInvitationCheckGetUserByIdsV2User.BlockInfo, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckGetUserByIdsV2User) GetBlockInfo() *CreateMatchingInvitationCheckGetUserByIdsV2UserBlockInfo {
	return v.BlockInfo
}

// CreateMatchingInvitationCheckGetUserByIdsV2UserBlockInfo includes the requested fields of the GraphQL type UserBlockInfo.
type CreateMatchingInvitationCheckGetUserByIdsV2UserBlockInfo struct {
	// 是否用户封禁，封禁则整个APP无法使用
	UserBlocked bool `json:"userBlocked"`
	// 是否匹配封禁，封禁则无法加入新的匹配
	MatchingBlocked bool `json:"matchingBlocked"`
}

// GetUserBlocked returns CreateMatchingInvitationCheckGetUserByIdsV2UserBlockInfo.UserBlocked, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckGetUserByIdsV2UserBlockInfo) GetUserBlocked() bool {
	return v.UserBlocked
}

// GetMatchingBlocked returns CreateMatchingInvitationCheckGetUserByIdsV2UserBlockInfo.MatchingBlocked, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckGetUserByIdsV2UserBlockInfo) GetMatchingBlocked() bool {
	return v.MatchingBlocked
}

// CreateMatchingInvitationCheckResponse is returned by CreateMatchingInvitationCheck on success.
type CreateMatchingInvitationCheckResponse struct {
	// 【话题】话题查询
	Topic *CreateMatchingInvitationCheckTopic `json:"topic"`
	// 【地区】根据地区代码查询地区信息
	Area *CreateMatchingInvitationCheckArea `json:"area"`
	// 【用户】根据ID批量获取用户，管理端使用，用户可以不存在
	GetUserByIdsV2 []*CreateMatchingInvitationCheckGetUserByIdsV2User `json:"getUserByIdsV2"`
	// 【黑名单】获取指定 userId 之间的黑名单关系
	BlacklistRelationship []*CreateMatchingInvitationCheckBlacklistRelationshipUserPair `json:"blacklistRelationship"`
}

// GetTopic returns CreateMatchingInvitationCheckResponse.Topic, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckResponse) GetTopic() *CreateMatchingInvitationCheckTopic {
	return v.Topic
}

// GetArea returns CreateMatchingInvitationCheckResponse.Area, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckResponse) GetArea() *CreateMatchingInvitationCheckArea {
	return v.Area
}

// GetGetUserByIdsV2 returns CreateMatchingInvitationCheckResponse.GetUserByIdsV2, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckResponse) GetGetUserByIdsV2() []*CreateMatchingInvitationCheckGetUserByIdsV2User {
	return v.GetUserByIdsV2
}

// GetBlacklistRelationship returns CreateMatchingInvitationCheckResponse.BlacklistRelationship, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckResponse) GetBlacklistRelationship() []*CreateMatchingInvitationCheckBlacklistRelationshipUserPair {
	return v.BlacklistRelationship
}

// CreateMatchingInvitationCheckTopic includes the requested fields of the GraphQL type Topic.
type CreateMatchingInvitationCheckTopic struct {
	// 话题ID
	Id string `json:"id"`
	// 名称
	Name string `json:"name"`
	// 是否可用
	Enable bool `json:"enable"`
}

// GetId returns CreateMatchingInvitationCheckTopic.Id, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckTopic) GetId() string { return v.Id }

// GetName returns CreateMatchingInvitationCheckTopic.Name, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckTopic) GetName() string { return v.Name }

// GetEnable returns CreateMatchingInvitationCheckTopic.Enable, and is useful for accessing the field via an interface.
func (v *CreateMatchingInvitationCheckTopic) GetEnable() bool { return v.Enable }

// CreateMotionCheckArea includes the requested fields of the GraphQL type Area.
type CreateMotionCheckArea struct {
	// 地区代码
	Code string `json:"code"`
	// 是否开通业务
	Enabled bool `json:"enabled"`
}

// GetCode returns CreateMotionCheckArea.Code, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckArea) GetCode() string { return v.Code }

// GetEnabled returns CreateMotionCheckArea.Enabled, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckArea) GetEnabled() bool { return v.Enabled }

// CreateMotionCheckLevelDetail includes the requested fields of the GraphQL type LevelDetail.
type CreateMotionCheckLevelDetail struct {
	// 当前等级的权益
	Rights *CreateMotionCheckLevelDetailRightsLevelRights `json:"rights"`
}

// GetRights returns CreateMotionCheckLevelDetail.Rights, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckLevelDetail) GetRights() *CreateMotionCheckLevelDetailRightsLevelRights {
	return v.Rights
}

// CreateMotionCheckLevelDetailRightsLevelRights includes the requested fields of the GraphQL type LevelRights.
type CreateMotionCheckLevelDetailRightsLevelRights struct {
	// 性别选择
	GenderSelection bool `json:"genderSelection"`
}

// GetGenderSelection returns CreateMotionCheckLevelDetailRightsLevelRights.GenderSelection, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckLevelDetailRightsLevelRights) GetGenderSelection() bool {
	return v.GenderSelection
}

// CreateMotionCheckResponse is returned by CreateMotionCheck on success.
type CreateMotionCheckResponse struct {
	// 【话题】话题查询
	Topic *CreateMotionCheckTopic `json:"topic"`
	// 【地区】根据地区代码查询地区信息
	Area *CreateMotionCheckArea `json:"area"`
	// 【用户】获取用户信息
	User *CreateMotionCheckUser `json:"user"`
	// 【用户】 用户信息完整性检查
	UserInfoCompletenessCheck *CreateMotionCheckUserInfoCompletenessCheckUserInfoCompleteness `json:"userInfoCompletenessCheck"`
	// 【用户】等级详情
	LevelDetail *CreateMotionCheckLevelDetail `json:"levelDetail"`
}

// GetTopic returns CreateMotionCheckResponse.Topic, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckResponse) GetTopic() *CreateMotionCheckTopic { return v.Topic }

// GetArea returns CreateMotionCheckResponse.Area, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckResponse) GetArea() *CreateMotionCheckArea { return v.Area }

// GetUser returns CreateMotionCheckResponse.User, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckResponse) GetUser() *CreateMotionCheckUser { return v.User }

// GetUserInfoCompletenessCheck returns CreateMotionCheckResponse.UserInfoCompletenessCheck, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckResponse) GetUserInfoCompletenessCheck() *CreateMotionCheckUserInfoCompletenessCheckUserInfoCompleteness {
	return v.UserInfoCompletenessCheck
}

// GetLevelDetail returns CreateMotionCheckResponse.LevelDetail, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckResponse) GetLevelDetail() *CreateMotionCheckLevelDetail {
	return v.LevelDetail
}

// CreateMotionCheckTopic includes the requested fields of the GraphQL type Topic.
type CreateMotionCheckTopic struct {
	// 话题ID
	Id string `json:"id"`
	// 是否可用
	Enable bool `json:"enable"`
}

// GetId returns CreateMotionCheckTopic.Id, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckTopic) GetId() string { return v.Id }

// GetEnable returns CreateMotionCheckTopic.Enable, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckTopic) GetEnable() bool { return v.Enable }

// CreateMotionCheckUser includes the requested fields of the GraphQL type User.
type CreateMotionCheckUser struct {
	// 用户封禁信息
	BlockInfo *CreateMotionCheckUserBlockInfo `json:"blockInfo"`
}

// GetBlockInfo returns CreateMotionCheckUser.BlockInfo, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckUser) GetBlockInfo() *CreateMotionCheckUserBlockInfo { return v.BlockInfo }

// CreateMotionCheckUserBlockInfo includes the requested fields of the GraphQL type UserBlockInfo.
type CreateMotionCheckUserBlockInfo struct {
	// 是否用户封禁，封禁则整个APP无法使用
	UserBlocked bool `json:"userBlocked"`
	// 是否匹配封禁，封禁则无法加入新的匹配
	MatchingBlocked bool `json:"matchingBlocked"`
}

// GetUserBlocked returns CreateMotionCheckUserBlockInfo.UserBlocked, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckUserBlockInfo) GetUserBlocked() bool { return v.UserBlocked }

// GetMatchingBlocked returns CreateMotionCheckUserBlockInfo.MatchingBlocked, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckUserBlockInfo) GetMatchingBlocked() bool { return v.MatchingBlocked }

// CreateMotionCheckUserInfoCompletenessCheckUserInfoCompleteness includes the requested fields of the GraphQL type UserInfoCompleteness.
type CreateMotionCheckUserInfoCompletenessCheckUserInfoCompleteness struct {
	// 信息是否全部填写
	Filled bool `json:"filled"`
}

// GetFilled returns CreateMotionCheckUserInfoCompletenessCheckUserInfoCompleteness.Filled, and is useful for accessing the field via an interface.
func (v *CreateMotionCheckUserInfoCompletenessCheckUserInfoCompleteness) GetFilled() bool {
	return v.Filled
}

type ExtraOptionKey string

const (
	ExtraOptionKeyNone    ExtraOptionKey = "None"
	ExtraOptionKeySinger  ExtraOptionKey = "Singer"
	ExtraOptionKeyConcert ExtraOptionKey = "Concert"
	ExtraOptionKeyPoi     ExtraOptionKey = "POI"
	ExtraOptionKeyCity    ExtraOptionKey = "City"
)

// GetAllTopicAndCategoryAndTopicNameAreasArea includes the requested fields of the GraphQL type Area.
type GetAllTopicAndCategoryAndTopicNameAreasArea struct {
	// 地区代码
	Code string `json:"code"`
	// 名称
	Name string `json:"name"`
}

// GetCode returns GetAllTopicAndCategoryAndTopicNameAreasArea.Code, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameAreasArea) GetCode() string { return v.Code }

// GetName returns GetAllTopicAndCategoryAndTopicNameAreasArea.Name, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameAreasArea) GetName() string { return v.Name }

// GetAllTopicAndCategoryAndTopicNameResponse is returned by GetAllTopicAndCategoryAndTopicName on success.
type GetAllTopicAndCategoryAndTopicNameResponse struct {
	// 【话题】类别列表查询
	TopicCategories []*GetAllTopicAndCategoryAndTopicNameTopicCategoriesTopicCategory `json:"topicCategories"`
	// 【话题】列表查询
	Topics []*GetAllTopicAndCategoryAndTopicNameTopicsTopic `json:"topics"`
	// 【地区】地区列表查询
	Areas []*GetAllTopicAndCategoryAndTopicNameAreasArea `json:"areas"`
}

// GetTopicCategories returns GetAllTopicAndCategoryAndTopicNameResponse.TopicCategories, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameResponse) GetTopicCategories() []*GetAllTopicAndCategoryAndTopicNameTopicCategoriesTopicCategory {
	return v.TopicCategories
}

// GetTopics returns GetAllTopicAndCategoryAndTopicNameResponse.Topics, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameResponse) GetTopics() []*GetAllTopicAndCategoryAndTopicNameTopicsTopic {
	return v.Topics
}

// GetAreas returns GetAllTopicAndCategoryAndTopicNameResponse.Areas, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameResponse) GetAreas() []*GetAllTopicAndCategoryAndTopicNameAreasArea {
	return v.Areas
}

// GetAllTopicAndCategoryAndTopicNameTopicCategoriesTopicCategory includes the requested fields of the GraphQL type TopicCategory.
type GetAllTopicAndCategoryAndTopicNameTopicCategoriesTopicCategory struct {
	// 分类名称
	Name string `json:"name"`
	// 类别描述
	Desc string `json:"desc"`
}

// GetName returns GetAllTopicAndCategoryAndTopicNameTopicCategoriesTopicCategory.Name, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameTopicCategoriesTopicCategory) GetName() string {
	return v.Name
}

// GetDesc returns GetAllTopicAndCategoryAndTopicNameTopicCategoriesTopicCategory.Desc, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameTopicCategoriesTopicCategory) GetDesc() string {
	return v.Desc
}

// GetAllTopicAndCategoryAndTopicNameTopicsTopic includes the requested fields of the GraphQL type Topic.
type GetAllTopicAndCategoryAndTopicNameTopicsTopic struct {
	// 话题ID
	Id string `json:"id"`
	// 名称
	Name string `json:"name"`
}

// GetId returns GetAllTopicAndCategoryAndTopicNameTopicsTopic.Id, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameTopicsTopic) GetId() string { return v.Id }

// GetName returns GetAllTopicAndCategoryAndTopicNameTopicsTopic.Name, and is useful for accessing the field via an interface.
func (v *GetAllTopicAndCategoryAndTopicNameTopicsTopic) GetName() string { return v.Name }

// GetAreaArea includes the requested fields of the GraphQL type Area.
type GetAreaArea struct {
	// 地区代码
	Code string `json:"code"`
	// 名称
	Name string `json:"name"`
	// 层级
	Depth int `json:"depth"`
}

// GetCode returns GetAreaArea.Code, and is useful for accessing the field via an interface.
func (v *GetAreaArea) GetCode() string { return v.Code }

// GetName returns GetAreaArea.Name, and is useful for accessing the field via an interface.
func (v *GetAreaArea) GetName() string { return v.Name }

// GetDepth returns GetAreaArea.Depth, and is useful for accessing the field via an interface.
func (v *GetAreaArea) GetDepth() int { return v.Depth }

// GetAreaResponse is returned by GetArea on success.
type GetAreaResponse struct {
	// 【地区】根据地区代码查询地区信息
	Area *GetAreaArea `json:"area"`
}

// GetArea returns GetAreaResponse.Area, and is useful for accessing the field via an interface.
func (v *GetAreaResponse) GetArea() *GetAreaArea { return v.Area }

// GetAvatarByIDsGetUserByIdsUser includes the requested fields of the GraphQL type User.
type GetAvatarByIDsGetUserByIdsUser struct {
	// 用户ID
	Id string `json:"id"`
	// 昵称
	Nickname string `json:"nickname"`
	// 头像URL
	Avatar string `json:"avatar"`
}

// GetId returns GetAvatarByIDsGetUserByIdsUser.Id, and is useful for accessing the field via an interface.
func (v *GetAvatarByIDsGetUserByIdsUser) GetId() string { return v.Id }

// GetNickname returns GetAvatarByIDsGetUserByIdsUser.Nickname, and is useful for accessing the field via an interface.
func (v *GetAvatarByIDsGetUserByIdsUser) GetNickname() string { return v.Nickname }

// GetAvatar returns GetAvatarByIDsGetUserByIdsUser.Avatar, and is useful for accessing the field via an interface.
func (v *GetAvatarByIDsGetUserByIdsUser) GetAvatar() string { return v.Avatar }

// GetAvatarByIDsResponse is returned by GetAvatarByIDs on success.
type GetAvatarByIDsResponse struct {
	// 【用户】根据ID批量获取
	GetUserByIds []*GetAvatarByIDsGetUserByIdsUser `json:"getUserByIds"`
}

// GetGetUserByIds returns GetAvatarByIDsResponse.GetUserByIds, and is useful for accessing the field via an interface.
func (v *GetAvatarByIDsResponse) GetGetUserByIds() []*GetAvatarByIDsGetUserByIdsUser {
	return v.GetUserByIds
}

// GetBlacklistRelationshipBlacklistRelationshipUserPair includes the requested fields of the GraphQL type UserPair.
type GetBlacklistRelationshipBlacklistRelationshipUserPair struct {
	A string `json:"a"`
	B string `json:"b"`
}

// GetA returns GetBlacklistRelationshipBlacklistRelationshipUserPair.A, and is useful for accessing the field via an interface.
func (v *GetBlacklistRelationshipBlacklistRelationshipUserPair) GetA() string { return v.A }

// GetB returns GetBlacklistRelationshipBlacklistRelationshipUserPair.B, and is useful for accessing the field via an interface.
func (v *GetBlacklistRelationshipBlacklistRelationshipUserPair) GetB() string { return v.B }

// GetBlacklistRelationshipResponse is returned by GetBlacklistRelationship on success.
type GetBlacklistRelationshipResponse struct {
	// 【黑名单】获取指定 userId 之间的黑名单关系
	BlacklistRelationship []*GetBlacklistRelationshipBlacklistRelationshipUserPair `json:"blacklistRelationship"`
}

// GetBlacklistRelationship returns GetBlacklistRelationshipResponse.BlacklistRelationship, and is useful for accessing the field via an interface.
func (v *GetBlacklistRelationshipResponse) GetBlacklistRelationship() []*GetBlacklistRelationshipBlacklistRelationshipUserPair {
	return v.BlacklistRelationship
}

// GetTopicConfigOptionResponse is returned by GetTopicConfigOption on success.
type GetTopicConfigOptionResponse struct {
	TopicOptionConfig *GetTopicConfigOptionTopicOptionConfig `json:"topicOptionConfig"`
}

// GetTopicOptionConfig returns GetTopicConfigOptionResponse.TopicOptionConfig, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionResponse) GetTopicOptionConfig() *GetTopicConfigOptionTopicOptionConfig {
	return v.TopicOptionConfig
}

// GetTopicConfigOptionTopicOptionConfig includes the requested fields of the GraphQL type TopicOptionConfig.
type GetTopicConfigOptionTopicOptionConfig struct {
	TopicOptionConfigFields `json:"-"`
}

// GetTopicId returns GetTopicConfigOptionTopicOptionConfig.TopicId, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionTopicOptionConfig) GetTopicId() string {
	return v.TopicOptionConfigFields.TopicId
}

// GetTimeWeight returns GetTopicConfigOptionTopicOptionConfig.TimeWeight, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionTopicOptionConfig) GetTimeWeight() int {
	return v.TopicOptionConfigFields.TimeWeight
}

// GetThreshold returns GetTopicConfigOptionTopicOptionConfig.Threshold, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionTopicOptionConfig) GetThreshold() int {
	return v.TopicOptionConfigFields.Threshold
}

// GetFuzzyMatchingTopic returns GetTopicConfigOptionTopicOptionConfig.FuzzyMatchingTopic, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionTopicOptionConfig) GetFuzzyMatchingTopic() bool {
	return v.TopicOptionConfigFields.FuzzyMatchingTopic
}

// GetAllowFuzzyMatching returns GetTopicConfigOptionTopicOptionConfig.AllowFuzzyMatching, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionTopicOptionConfig) GetAllowFuzzyMatching() bool {
	return v.TopicOptionConfigFields.AllowFuzzyMatching
}

// GetDelayMinuteToPairWithFuzzyTopic returns GetTopicConfigOptionTopicOptionConfig.DelayMinuteToPairWithFuzzyTopic, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionTopicOptionConfig) GetDelayMinuteToPairWithFuzzyTopic() int {
	return v.TopicOptionConfigFields.DelayMinuteToPairWithFuzzyTopic
}

// GetProperties returns GetTopicConfigOptionTopicOptionConfig.Properties, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionTopicOptionConfig) GetProperties() []*TopicOptionConfigFieldsPropertiesTopicOptionProperty {
	return v.TopicOptionConfigFields.Properties
}

func (v *GetTopicConfigOptionTopicOptionConfig) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetTopicConfigOptionTopicOptionConfig
		graphql.NoUnmarshalJSON
	}
	firstPass.GetTopicConfigOptionTopicOptionConfig = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.TopicOptionConfigFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalGetTopicConfigOptionTopicOptionConfig struct {
	TopicId string `json:"topicId"`

	TimeWeight int `json:"timeWeight"`

	Threshold int `json:"threshold"`

	FuzzyMatchingTopic bool `json:"fuzzyMatchingTopic"`

	AllowFuzzyMatching bool `json:"allowFuzzyMatching"`

	DelayMinuteToPairWithFuzzyTopic int `json:"delayMinuteToPairWithFuzzyTopic"`

	Properties []*TopicOptionConfigFieldsPropertiesTopicOptionProperty `json:"properties"`
}

func (v *GetTopicConfigOptionTopicOptionConfig) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetTopicConfigOptionTopicOptionConfig) __premarshalJSON() (*__premarshalGetTopicConfigOptionTopicOptionConfig, error) {
	var retval __premarshalGetTopicConfigOptionTopicOptionConfig

	retval.TopicId = v.TopicOptionConfigFields.TopicId
	retval.TimeWeight = v.TopicOptionConfigFields.TimeWeight
	retval.Threshold = v.TopicOptionConfigFields.Threshold
	retval.FuzzyMatchingTopic = v.TopicOptionConfigFields.FuzzyMatchingTopic
	retval.AllowFuzzyMatching = v.TopicOptionConfigFields.AllowFuzzyMatching
	retval.DelayMinuteToPairWithFuzzyTopic = v.TopicOptionConfigFields.DelayMinuteToPairWithFuzzyTopic
	retval.Properties = v.TopicOptionConfigFields.Properties
	return &retval, nil
}

// GetTopicConfigOptionsResponse is returned by GetTopicConfigOptions on success.
type GetTopicConfigOptionsResponse struct {
	TopicOptionConfigs []*GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig `json:"topicOptionConfigs"`
}

// GetTopicOptionConfigs returns GetTopicConfigOptionsResponse.TopicOptionConfigs, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionsResponse) GetTopicOptionConfigs() []*GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig {
	return v.TopicOptionConfigs
}

// GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig includes the requested fields of the GraphQL type TopicOptionConfig.
type GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig struct {
	TopicOptionConfigFields `json:"-"`
}

// GetTopicId returns GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig.TopicId, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) GetTopicId() string {
	return v.TopicOptionConfigFields.TopicId
}

// GetTimeWeight returns GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig.TimeWeight, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) GetTimeWeight() int {
	return v.TopicOptionConfigFields.TimeWeight
}

// GetThreshold returns GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig.Threshold, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) GetThreshold() int {
	return v.TopicOptionConfigFields.Threshold
}

// GetFuzzyMatchingTopic returns GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig.FuzzyMatchingTopic, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) GetFuzzyMatchingTopic() bool {
	return v.TopicOptionConfigFields.FuzzyMatchingTopic
}

// GetAllowFuzzyMatching returns GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig.AllowFuzzyMatching, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) GetAllowFuzzyMatching() bool {
	return v.TopicOptionConfigFields.AllowFuzzyMatching
}

// GetDelayMinuteToPairWithFuzzyTopic returns GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig.DelayMinuteToPairWithFuzzyTopic, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) GetDelayMinuteToPairWithFuzzyTopic() int {
	return v.TopicOptionConfigFields.DelayMinuteToPairWithFuzzyTopic
}

// GetProperties returns GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig.Properties, and is useful for accessing the field via an interface.
func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) GetProperties() []*TopicOptionConfigFieldsPropertiesTopicOptionProperty {
	return v.TopicOptionConfigFields.Properties
}

func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig
		graphql.NoUnmarshalJSON
	}
	firstPass.GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.TopicOptionConfigFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalGetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig struct {
	TopicId string `json:"topicId"`

	TimeWeight int `json:"timeWeight"`

	Threshold int `json:"threshold"`

	FuzzyMatchingTopic bool `json:"fuzzyMatchingTopic"`

	AllowFuzzyMatching bool `json:"allowFuzzyMatching"`

	DelayMinuteToPairWithFuzzyTopic int `json:"delayMinuteToPairWithFuzzyTopic"`

	Properties []*TopicOptionConfigFieldsPropertiesTopicOptionProperty `json:"properties"`
}

func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig) __premarshalJSON() (*__premarshalGetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig, error) {
	var retval __premarshalGetTopicConfigOptionsTopicOptionConfigsTopicOptionConfig

	retval.TopicId = v.TopicOptionConfigFields.TopicId
	retval.TimeWeight = v.TopicOptionConfigFields.TimeWeight
	retval.Threshold = v.TopicOptionConfigFields.Threshold
	retval.FuzzyMatchingTopic = v.TopicOptionConfigFields.FuzzyMatchingTopic
	retval.AllowFuzzyMatching = v.TopicOptionConfigFields.AllowFuzzyMatching
	retval.DelayMinuteToPairWithFuzzyTopic = v.TopicOptionConfigFields.DelayMinuteToPairWithFuzzyTopic
	retval.Properties = v.TopicOptionConfigFields.Properties
	return &retval, nil
}

// GetTopicNameResponse is returned by GetTopicName on success.
type GetTopicNameResponse struct {
	// 【话题】话题查询
	Topic *GetTopicNameTopic `json:"topic"`
}

// GetTopic returns GetTopicNameResponse.Topic, and is useful for accessing the field via an interface.
func (v *GetTopicNameResponse) GetTopic() *GetTopicNameTopic { return v.Topic }

// GetTopicNameTopic includes the requested fields of the GraphQL type Topic.
type GetTopicNameTopic struct {
	// 话题ID
	Id string `json:"id"`
	// 名称
	Name string `json:"name"`
}

// GetId returns GetTopicNameTopic.Id, and is useful for accessing the field via an interface.
func (v *GetTopicNameTopic) GetId() string { return v.Id }

// GetName returns GetTopicNameTopic.Name, and is useful for accessing the field via an interface.
func (v *GetTopicNameTopic) GetName() string { return v.Name }

// GetTopicResponse is returned by GetTopic on success.
type GetTopicResponse struct {
	// 【话题】话题查询
	Topic *GetTopicTopic `json:"topic"`
}

// GetTopic returns GetTopicResponse.Topic, and is useful for accessing the field via an interface.
func (v *GetTopicResponse) GetTopic() *GetTopicTopic { return v.Topic }

// GetTopicTopic includes the requested fields of the GraphQL type Topic.
type GetTopicTopic struct {
	// 话题ID
	Id string `json:"id"`
}

// GetId returns GetTopicTopic.Id, and is useful for accessing the field via an interface.
func (v *GetTopicTopic) GetId() string { return v.Id }

// GetTopicsResponse is returned by GetTopics on success.
type GetTopicsResponse struct {
	// 【话题】列表查询
	Topics []*GetTopicsTopicsTopic `json:"topics"`
}

// GetTopics returns GetTopicsResponse.Topics, and is useful for accessing the field via an interface.
func (v *GetTopicsResponse) GetTopics() []*GetTopicsTopicsTopic { return v.Topics }

// GetTopicsTopicsTopic includes the requested fields of the GraphQL type Topic.
type GetTopicsTopicsTopic struct {
	// 话题ID
	Id string `json:"id"`
	// 类别
	Category string `json:"category"`
}

// GetId returns GetTopicsTopicsTopic.Id, and is useful for accessing the field via an interface.
func (v *GetTopicsTopicsTopic) GetId() string { return v.Id }

// GetCategory returns GetTopicsTopicsTopic.Category, and is useful for accessing the field via an interface.
func (v *GetTopicsTopicsTopic) GetCategory() string { return v.Category }

// GetUserByIDsGetUserByIdsUser includes the requested fields of the GraphQL type User.
type GetUserByIDsGetUserByIdsUser struct {
	// 用户ID
	Id string `json:"id"`
	// 性别：男——M；女——F
	Gender string `json:"gender"`
	// 用户等级
	Level int `json:"level"`
}

// GetId returns GetUserByIDsGetUserByIdsUser.Id, and is useful for accessing the field via an interface.
func (v *GetUserByIDsGetUserByIdsUser) GetId() string { return v.Id }

// GetGender returns GetUserByIDsGetUserByIdsUser.Gender, and is useful for accessing the field via an interface.
func (v *GetUserByIDsGetUserByIdsUser) GetGender() string { return v.Gender }

// GetLevel returns GetUserByIDsGetUserByIdsUser.Level, and is useful for accessing the field via an interface.
func (v *GetUserByIDsGetUserByIdsUser) GetLevel() int { return v.Level }

// GetUserByIDsResponse is returned by GetUserByIDs on success.
type GetUserByIDsResponse struct {
	// 【用户】根据ID批量获取
	GetUserByIds []*GetUserByIDsGetUserByIdsUser `json:"getUserByIds"`
}

// GetGetUserByIds returns GetUserByIDsResponse.GetUserByIds, and is useful for accessing the field via an interface.
func (v *GetUserByIDsResponse) GetGetUserByIds() []*GetUserByIDsGetUserByIdsUser {
	return v.GetUserByIds
}

type GraphQLPaginator struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

// GetPage returns GraphQLPaginator.Page, and is useful for accessing the field via an interface.
func (v *GraphQLPaginator) GetPage() int { return v.Page }

// GetSize returns GraphQLPaginator.Size, and is useful for accessing the field via an interface.
func (v *GraphQLPaginator) GetSize() int { return v.Size }

// TopicOptionConfigFields includes the GraphQL fields of TopicOptionConfig requested by the fragment TopicOptionConfigFields.
type TopicOptionConfigFields struct {
	TopicId    string `json:"topicId"`
	TimeWeight int    `json:"timeWeight"`
	Threshold  int    `json:"threshold"`
	// 是否是模糊匹配话题
	FuzzyMatchingTopic bool `json:"fuzzyMatchingTopic"`
	// 是否允许被模糊匹配
	AllowFuzzyMatching bool `json:"allowFuzzyMatching"`
	// 等待多少分钟后可进行模糊匹配
	DelayMinuteToPairWithFuzzyTopic int                                                     `json:"delayMinuteToPairWithFuzzyTopic"`
	Properties                      []*TopicOptionConfigFieldsPropertiesTopicOptionProperty `json:"properties"`
}

// GetTopicId returns TopicOptionConfigFields.TopicId, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFields) GetTopicId() string { return v.TopicId }

// GetTimeWeight returns TopicOptionConfigFields.TimeWeight, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFields) GetTimeWeight() int { return v.TimeWeight }

// GetThreshold returns TopicOptionConfigFields.Threshold, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFields) GetThreshold() int { return v.Threshold }

// GetFuzzyMatchingTopic returns TopicOptionConfigFields.FuzzyMatchingTopic, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFields) GetFuzzyMatchingTopic() bool { return v.FuzzyMatchingTopic }

// GetAllowFuzzyMatching returns TopicOptionConfigFields.AllowFuzzyMatching, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFields) GetAllowFuzzyMatching() bool { return v.AllowFuzzyMatching }

// GetDelayMinuteToPairWithFuzzyTopic returns TopicOptionConfigFields.DelayMinuteToPairWithFuzzyTopic, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFields) GetDelayMinuteToPairWithFuzzyTopic() int {
	return v.DelayMinuteToPairWithFuzzyTopic
}

// GetProperties returns TopicOptionConfigFields.Properties, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFields) GetProperties() []*TopicOptionConfigFieldsPropertiesTopicOptionProperty {
	return v.Properties
}

// TopicOptionConfigFieldsPropertiesTopicOptionProperty includes the requested fields of the GraphQL type TopicOptionProperty.
type TopicOptionConfigFieldsPropertiesTopicOptionProperty struct {
	Id               string                                                                    `json:"id"`
	Required         bool                                                                      `json:"required"`
	Name             string                                                                    `json:"name"`
	Weight           int                                                                       `json:"weight"`
	Comparable       bool                                                                      `json:"comparable"`
	Enabled          bool                                                                      `json:"enabled"`
	MaxSelection     int                                                                       `json:"maxSelection"`
	DefaultSelectAll bool                                                                      `json:"defaultSelectAll"`
	Options          []*TopicOptionConfigFieldsPropertiesTopicOptionPropertyOptionsTopicOption `json:"options"`
	ExtraOptionKey   ExtraOptionKey                                                            `json:"extraOptionKey"`
}

// GetId returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.Id, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetId() string { return v.Id }

// GetRequired returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.Required, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetRequired() bool { return v.Required }

// GetName returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.Name, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetName() string { return v.Name }

// GetWeight returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.Weight, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetWeight() int { return v.Weight }

// GetComparable returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.Comparable, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetComparable() bool {
	return v.Comparable
}

// GetEnabled returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.Enabled, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetEnabled() bool { return v.Enabled }

// GetMaxSelection returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.MaxSelection, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetMaxSelection() int {
	return v.MaxSelection
}

// GetDefaultSelectAll returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.DefaultSelectAll, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetDefaultSelectAll() bool {
	return v.DefaultSelectAll
}

// GetOptions returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.Options, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetOptions() []*TopicOptionConfigFieldsPropertiesTopicOptionPropertyOptionsTopicOption {
	return v.Options
}

// GetExtraOptionKey returns TopicOptionConfigFieldsPropertiesTopicOptionProperty.ExtraOptionKey, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionProperty) GetExtraOptionKey() ExtraOptionKey {
	return v.ExtraOptionKey
}

// TopicOptionConfigFieldsPropertiesTopicOptionPropertyOptionsTopicOption includes the requested fields of the GraphQL type TopicOption.
type TopicOptionConfigFieldsPropertiesTopicOptionPropertyOptionsTopicOption struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
}

// GetName returns TopicOptionConfigFieldsPropertiesTopicOptionPropertyOptionsTopicOption.Name, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionPropertyOptionsTopicOption) GetName() string {
	return v.Name
}

// GetValue returns TopicOptionConfigFieldsPropertiesTopicOptionPropertyOptionsTopicOption.Value, and is useful for accessing the field via an interface.
func (v *TopicOptionConfigFieldsPropertiesTopicOptionPropertyOptionsTopicOption) GetValue() int {
	return v.Value
}

// __CreateMatchingCheckInput is used internally by genqlient
type __CreateMatchingCheckInput struct {
	TopicId string `json:"topicId"`
	CityId  string `json:"cityId"`
	UserId  string `json:"userId"`
}

// GetTopicId returns __CreateMatchingCheckInput.TopicId, and is useful for accessing the field via an interface.
func (v *__CreateMatchingCheckInput) GetTopicId() string { return v.TopicId }

// GetCityId returns __CreateMatchingCheckInput.CityId, and is useful for accessing the field via an interface.
func (v *__CreateMatchingCheckInput) GetCityId() string { return v.CityId }

// GetUserId returns __CreateMatchingCheckInput.UserId, and is useful for accessing the field via an interface.
func (v *__CreateMatchingCheckInput) GetUserId() string { return v.UserId }

// __CreateMatchingInvitationCheckInput is used internally by genqlient
type __CreateMatchingInvitationCheckInput struct {
	TopicId string   `json:"topicId"`
	CityId  string   `json:"cityId"`
	Ids     []string `json:"ids"`
}

// GetTopicId returns __CreateMatchingInvitationCheckInput.TopicId, and is useful for accessing the field via an interface.
func (v *__CreateMatchingInvitationCheckInput) GetTopicId() string { return v.TopicId }

// GetCityId returns __CreateMatchingInvitationCheckInput.CityId, and is useful for accessing the field via an interface.
func (v *__CreateMatchingInvitationCheckInput) GetCityId() string { return v.CityId }

// GetIds returns __CreateMatchingInvitationCheckInput.Ids, and is useful for accessing the field via an interface.
func (v *__CreateMatchingInvitationCheckInput) GetIds() []string { return v.Ids }

// __CreateMotionCheckInput is used internally by genqlient
type __CreateMotionCheckInput struct {
	TopicId string `json:"topicId"`
	CityId  string `json:"cityId"`
	UserId  string `json:"userId"`
}

// GetTopicId returns __CreateMotionCheckInput.TopicId, and is useful for accessing the field via an interface.
func (v *__CreateMotionCheckInput) GetTopicId() string { return v.TopicId }

// GetCityId returns __CreateMotionCheckInput.CityId, and is useful for accessing the field via an interface.
func (v *__CreateMotionCheckInput) GetCityId() string { return v.CityId }

// GetUserId returns __CreateMotionCheckInput.UserId, and is useful for accessing the field via an interface.
func (v *__CreateMotionCheckInput) GetUserId() string { return v.UserId }

// __GetAllTopicAndCategoryAndTopicNameInput is used internally by genqlient
type __GetAllTopicAndCategoryAndTopicNameInput struct {
	Paginator *GraphQLPaginator `json:"paginator,omitempty"`
}

// GetPaginator returns __GetAllTopicAndCategoryAndTopicNameInput.Paginator, and is useful for accessing the field via an interface.
func (v *__GetAllTopicAndCategoryAndTopicNameInput) GetPaginator() *GraphQLPaginator {
	return v.Paginator
}

// __GetAreaInput is used internally by genqlient
type __GetAreaInput struct {
	Id string `json:"id"`
}

// GetId returns __GetAreaInput.Id, and is useful for accessing the field via an interface.
func (v *__GetAreaInput) GetId() string { return v.Id }

// __GetAvatarByIDsInput is used internally by genqlient
type __GetAvatarByIDsInput struct {
	Ids []string `json:"ids"`
}

// GetIds returns __GetAvatarByIDsInput.Ids, and is useful for accessing the field via an interface.
func (v *__GetAvatarByIDsInput) GetIds() []string { return v.Ids }

// __GetBlacklistRelationshipInput is used internally by genqlient
type __GetBlacklistRelationshipInput struct {
	Ids []string `json:"ids"`
}

// GetIds returns __GetBlacklistRelationshipInput.Ids, and is useful for accessing the field via an interface.
func (v *__GetBlacklistRelationshipInput) GetIds() []string { return v.Ids }

// __GetTopicConfigOptionInput is used internally by genqlient
type __GetTopicConfigOptionInput struct {
	TopicId string `json:"topicId"`
}

// GetTopicId returns __GetTopicConfigOptionInput.TopicId, and is useful for accessing the field via an interface.
func (v *__GetTopicConfigOptionInput) GetTopicId() string { return v.TopicId }

// __GetTopicConfigOptionsInput is used internally by genqlient
type __GetTopicConfigOptionsInput struct {
	Paginator *GraphQLPaginator `json:"paginator,omitempty"`
}

// GetPaginator returns __GetTopicConfigOptionsInput.Paginator, and is useful for accessing the field via an interface.
func (v *__GetTopicConfigOptionsInput) GetPaginator() *GraphQLPaginator { return v.Paginator }

// __GetTopicInput is used internally by genqlient
type __GetTopicInput struct {
	Id string `json:"id"`
}

// GetId returns __GetTopicInput.Id, and is useful for accessing the field via an interface.
func (v *__GetTopicInput) GetId() string { return v.Id }

// __GetTopicNameInput is used internally by genqlient
type __GetTopicNameInput struct {
	Id string `json:"id"`
}

// GetId returns __GetTopicNameInput.Id, and is useful for accessing the field via an interface.
func (v *__GetTopicNameInput) GetId() string { return v.Id }

// __GetTopicsInput is used internally by genqlient
type __GetTopicsInput struct {
	Paginator *GraphQLPaginator `json:"paginator,omitempty"`
}

// GetPaginator returns __GetTopicsInput.Paginator, and is useful for accessing the field via an interface.
func (v *__GetTopicsInput) GetPaginator() *GraphQLPaginator { return v.Paginator }

// __GetUserByIDsInput is used internally by genqlient
type __GetUserByIDsInput struct {
	Ids []string `json:"ids"`
}

// GetIds returns __GetUserByIDsInput.Ids, and is useful for accessing the field via an interface.
func (v *__GetUserByIDsInput) GetIds() []string { return v.Ids }

// The query or mutation executed by CreateMatchingCheck.
const CreateMatchingCheck_Operation = `
query CreateMatchingCheck ($topicId: String!, $cityId: AreaCode!, $userId: String!) {
	topic(id: $topicId) {
		id
		enable
	}
	area(code: $cityId) {
		code
		enabled
	}
	user(id: $userId) {
		blockInfo {
			userBlocked
			matchingBlocked
		}
	}
	userInfoCompletenessCheck(userId: $userId) {
		filled
	}
	levelDetail(userId: $userId) {
		rights {
			genderSelection(userId: $userId)
		}
	}
}
`

func CreateMatchingCheck(
	ctx context.Context,
	client graphql.Client,
	topicId string,
	cityId string,
	userId string,
) (*CreateMatchingCheckResponse, error) {
	req := &graphql.Request{
		OpName: "CreateMatchingCheck",
		Query:  CreateMatchingCheck_Operation,
		Variables: &__CreateMatchingCheckInput{
			TopicId: topicId,
			CityId:  cityId,
			UserId:  userId,
		},
	}
	var err error

	var data CreateMatchingCheckResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by CreateMatchingInvitationCheck.
const CreateMatchingInvitationCheck_Operation = `
query CreateMatchingInvitationCheck ($topicId: String!, $cityId: AreaCode!, $ids: [String!]!) {
	topic(id: $topicId) {
		id
		name
		enable
	}
	area(code: $cityId) {
		code
		enabled
	}
	getUserByIdsV2(ids: $ids) {
		id
		blockInfo {
			userBlocked
			matchingBlocked
		}
	}
	blacklistRelationship(ids: $ids) {
		a
		b
	}
}
`

func CreateMatchingInvitationCheck(
	ctx context.Context,
	client graphql.Client,
	topicId string,
	cityId string,
	ids []string,
) (*CreateMatchingInvitationCheckResponse, error) {
	req := &graphql.Request{
		OpName: "CreateMatchingInvitationCheck",
		Query:  CreateMatchingInvitationCheck_Operation,
		Variables: &__CreateMatchingInvitationCheckInput{
			TopicId: topicId,
			CityId:  cityId,
			Ids:     ids,
		},
	}
	var err error

	var data CreateMatchingInvitationCheckResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by CreateMotionCheck.
const CreateMotionCheck_Operation = `
query CreateMotionCheck ($topicId: String!, $cityId: AreaCode!, $userId: String!) {
	topic(id: $topicId) {
		id
		enable
	}
	area(code: $cityId) {
		code
		enabled
	}
	user(id: $userId) {
		blockInfo {
			userBlocked
			matchingBlocked
		}
	}
	userInfoCompletenessCheck(userId: $userId) {
		filled
	}
	levelDetail(userId: $userId) {
		rights {
			genderSelection(userId: $userId)
		}
	}
}
`

func CreateMotionCheck(
	ctx context.Context,
	client graphql.Client,
	topicId string,
	cityId string,
	userId string,
) (*CreateMotionCheckResponse, error) {
	req := &graphql.Request{
		OpName: "CreateMotionCheck",
		Query:  CreateMotionCheck_Operation,
		Variables: &__CreateMotionCheckInput{
			TopicId: topicId,
			CityId:  cityId,
			UserId:  userId,
		},
	}
	var err error

	var data CreateMotionCheckResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetAllTopicAndCategoryAndTopicName.
const GetAllTopicAndCategoryAndTopicName_Operation = `
query GetAllTopicAndCategoryAndTopicName ($paginator: GraphQLPaginator!) {
	topicCategories(paginator: $paginator) {
		name
		desc
	}
	topics(paginator: $paginator) {
		id
		name
	}
	areas(filter: {depth:1}) {
		code
		name
	}
}
`

func GetAllTopicAndCategoryAndTopicName(
	ctx context.Context,
	client graphql.Client,
	paginator *GraphQLPaginator,
) (*GetAllTopicAndCategoryAndTopicNameResponse, error) {
	req := &graphql.Request{
		OpName: "GetAllTopicAndCategoryAndTopicName",
		Query:  GetAllTopicAndCategoryAndTopicName_Operation,
		Variables: &__GetAllTopicAndCategoryAndTopicNameInput{
			Paginator: paginator,
		},
	}
	var err error

	var data GetAllTopicAndCategoryAndTopicNameResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetArea.
const GetArea_Operation = `
query GetArea ($id: AreaCode!) {
	area(code: $id) {
		code
		name
		depth
	}
}
`

func GetArea(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*GetAreaResponse, error) {
	req := &graphql.Request{
		OpName: "GetArea",
		Query:  GetArea_Operation,
		Variables: &__GetAreaInput{
			Id: id,
		},
	}
	var err error

	var data GetAreaResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetAvatarByIDs.
const GetAvatarByIDs_Operation = `
query GetAvatarByIDs ($ids: [String!]!) {
	getUserByIds(ids: $ids) {
		id
		nickname
		avatar
	}
}
`

func GetAvatarByIDs(
	ctx context.Context,
	client graphql.Client,
	ids []string,
) (*GetAvatarByIDsResponse, error) {
	req := &graphql.Request{
		OpName: "GetAvatarByIDs",
		Query:  GetAvatarByIDs_Operation,
		Variables: &__GetAvatarByIDsInput{
			Ids: ids,
		},
	}
	var err error

	var data GetAvatarByIDsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetBlacklistRelationship.
const GetBlacklistRelationship_Operation = `
query GetBlacklistRelationship ($ids: [String!]!) {
	blacklistRelationship(ids: $ids) {
		a
		b
	}
}
`

func GetBlacklistRelationship(
	ctx context.Context,
	client graphql.Client,
	ids []string,
) (*GetBlacklistRelationshipResponse, error) {
	req := &graphql.Request{
		OpName: "GetBlacklistRelationship",
		Query:  GetBlacklistRelationship_Operation,
		Variables: &__GetBlacklistRelationshipInput{
			Ids: ids,
		},
	}
	var err error

	var data GetBlacklistRelationshipResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetTopic.
const GetTopic_Operation = `
query GetTopic ($id: String!) {
	topic(id: $id) {
		id
	}
}
`

func GetTopic(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*GetTopicResponse, error) {
	req := &graphql.Request{
		OpName: "GetTopic",
		Query:  GetTopic_Operation,
		Variables: &__GetTopicInput{
			Id: id,
		},
	}
	var err error

	var data GetTopicResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetTopicConfigOption.
const GetTopicConfigOption_Operation = `
query GetTopicConfigOption ($topicId: String!) {
	topicOptionConfig(topicId: $topicId) {
		... TopicOptionConfigFields
	}
}
fragment TopicOptionConfigFields on TopicOptionConfig {
	topicId
	timeWeight
	threshold
	fuzzyMatchingTopic
	allowFuzzyMatching
	delayMinuteToPairWithFuzzyTopic
	properties {
		id
		required
		name
		weight
		comparable
		enabled
		maxSelection
		defaultSelectAll
		options {
			name
			value
		}
		extraOptionKey
	}
}
`

func GetTopicConfigOption(
	ctx context.Context,
	client graphql.Client,
	topicId string,
) (*GetTopicConfigOptionResponse, error) {
	req := &graphql.Request{
		OpName: "GetTopicConfigOption",
		Query:  GetTopicConfigOption_Operation,
		Variables: &__GetTopicConfigOptionInput{
			TopicId: topicId,
		},
	}
	var err error

	var data GetTopicConfigOptionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetTopicConfigOptions.
const GetTopicConfigOptions_Operation = `
query GetTopicConfigOptions ($paginator: GraphQLPaginator!) {
	topicOptionConfigs(paginator: $paginator) {
		... TopicOptionConfigFields
	}
}
fragment TopicOptionConfigFields on TopicOptionConfig {
	topicId
	timeWeight
	threshold
	fuzzyMatchingTopic
	allowFuzzyMatching
	delayMinuteToPairWithFuzzyTopic
	properties {
		id
		required
		name
		weight
		comparable
		enabled
		maxSelection
		defaultSelectAll
		options {
			name
			value
		}
		extraOptionKey
	}
}
`

func GetTopicConfigOptions(
	ctx context.Context,
	client graphql.Client,
	paginator *GraphQLPaginator,
) (*GetTopicConfigOptionsResponse, error) {
	req := &graphql.Request{
		OpName: "GetTopicConfigOptions",
		Query:  GetTopicConfigOptions_Operation,
		Variables: &__GetTopicConfigOptionsInput{
			Paginator: paginator,
		},
	}
	var err error

	var data GetTopicConfigOptionsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetTopicName.
const GetTopicName_Operation = `
query GetTopicName ($id: String!) {
	topic(id: $id) {
		id
		name
	}
}
`

func GetTopicName(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*GetTopicNameResponse, error) {
	req := &graphql.Request{
		OpName: "GetTopicName",
		Query:  GetTopicName_Operation,
		Variables: &__GetTopicNameInput{
			Id: id,
		},
	}
	var err error

	var data GetTopicNameResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetTopics.
const GetTopics_Operation = `
query GetTopics ($paginator: GraphQLPaginator!) {
	topics(paginator: $paginator) {
		id
		category
	}
}
`

func GetTopics(
	ctx context.Context,
	client graphql.Client,
	paginator *GraphQLPaginator,
) (*GetTopicsResponse, error) {
	req := &graphql.Request{
		OpName: "GetTopics",
		Query:  GetTopics_Operation,
		Variables: &__GetTopicsInput{
			Paginator: paginator,
		},
	}
	var err error

	var data GetTopicsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetUserByIDs.
const GetUserByIDs_Operation = `
query GetUserByIDs ($ids: [String!]!) {
	getUserByIds(ids: $ids) {
		id
		gender
		level
	}
}
`

func GetUserByIDs(
	ctx context.Context,
	client graphql.Client,
	ids []string,
) (*GetUserByIDsResponse, error) {
	req := &graphql.Request{
		OpName: "GetUserByIDs",
		Query:  GetUserByIDs_Operation,
		Variables: &__GetUserByIDsInput{
			Ids: ids,
		},
	}
	var err error

	var data GetUserByIDsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
